# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mayner.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(457, 455)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 300, 121, 81))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"background-color: aqua;\n"
"color:steelblue;\n"
"font-size: 20px;\n"
"border: 3px solid indigo;\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: blue;\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 302, 131, 81))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"background-color: aqua;\n"
"color:steelblue;\n"
"font-size: 20px;\n"
"border: 3px solid indigo;\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: blue;\n"
"}")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(160, 300, 121, 81))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"background-color: aqua;\n"
"color:steelblue;\n"
"font-size: 20px;\n"
"border: 3px solid indigo;\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: blue;\n"
"}")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 200, 161, 51))
        self.label.setStyleSheet("QLabel {\n"
"background-color: aqua;\n"
"color:steelblue;\n"
"font-size: 20px;\n"
"border: 3px solid indigo;\n"
"border-radius: 15px;\n"
"}\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 30, 171, 91))
        self.label_2.setStyleSheet("QLabel {\n"
"background-color: aqua;\n"
"color:steelblue;\n"
"font-size: 20px;\n"
"border: 3px solid indigo;\n"
"border-radius: 15px;\n"
"}\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 457, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
